apps/talk/models.py
from datetime import datetime
from apps.app import db

class Text(db.Model):
    __tablename__ = "texts"

    id = db.Column(db.Integer, primary_key=True)
    textword = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(
        db.DateTime, default=datetime.now, onupdate=datetime.now
    )

apps/talk/views.py
from flask import Flask, render_template, Blueprint


talk = Blueprint(
    "talk",
    __name__,
    template_folder="templates",
    static_folder="static",
)


@talk.route("/")
def index():
    return render_template("talk/index.html")

@talk.route("/friends")
def friends():
    return render_template("talk/friends.html")


@talk.route("/chats")
def chats():
    return render_template("talk/chats.html")

@talk.route("/chat")
def chat():
    return render_template("talk/chat.html")

@talk.route("/chat/data")
def data():
    pass

apps/talk/templates/talk/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>채팅목록부분</title>
    <link rel="stylesheet" href="{{ url_for('talk.static', filename='chat.css') }}">

</head>
<body>
    <div class="chat-container">
        <header class="chat-header">
            <h1>채팅방</h1>
        </header>
        <main class="chat-main">
            <div class="chat-messages">
                <div class="message">
                    <p class="meta">나 <span>10:30 AM</span></p>
                    <p class="text">안녕하세요!</p>
                </div>
                <div class="message">
                    <p class="meta">누군가 <span>10:32 AM</span></p>
                    <p class="text">안녕하세요! 어떻게 지내세요?</p>
                </div>
                <div class="message">
                    <p class="meta">나 <span>10:34 AM</span></p>
                    <p class="text">잘 지내고 있어요! 다음에 밥 한번 먹어요!</p>
                </div>
                <div class="message">
                    <p class="meta">누군가 <span>10:36 AM</span></p>
                    <p class="text">시른데요</p>
                </div>
                <div class="message">
                    <p class="meta">누군가 <span>10:36 AM</span></p>
                    <p class="text">시른데요</p>
                </div>
                <div class="message">
                    <p class="meta">누군가 <span>10:36 AM</span></p>
                    <p class="text">시른데요</p>
                </div>
                <div class="message">
                    <p class="meta">누군가 <span>10:36 AM</span></p>
                    <p class="text">시른데요</p>
                </div>
            </div>
        </main>
        <footer class="chat-footer">
            <form id="chat-form">
                <input type="text" id="msg" placeholder="메시지를 입력하세요...">
                <button type="submit" class="btn">전송</button>
            </form>
        </footer>
    </div>
    <div class="outBtn">
        <a href="{{url_for('talk.chats')}}" class="out">나가기</a>
    </div>
</body>
</html>

apps/talk/templates/talk/chats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>채팅방</title>
    <link rel="stylesheet" href="{{ url_for('talk.static', filename='friends.css') }}">

</head>
<body>
    <nav class="navbar">
        <ul>
            <li>
                <a href="{{url_for('talk.friends')}}">
                    <img src="{{url_for('talk.static', filename='dog-friend.jpg')}}">
                </a>
            </li>
            <li>
                <a href="{{url_for('talk.chats')}}">
                    <img src="{{url_for('talk.static', filename='comics.png')}}">
                </a>
            </li>
        </ul>
    </nav>
    <div class="container">
        <header class="header">
            <h3>채팅</h3>
            <div class="header-buttons">
                <span class="header-button"></span>
                <span class="header-button"></span>
            </div>
        </header>
        <main class="main-content">
            <div class="chat-room-list">
                <a href="{{url_for('talk.chat')}}" class="friend-item">채팅방1</a>
                <br>
                <a href="{{url_for('talk.chat')}}" class="friend-item">채팅방2</a>
            </div>
        </main>
</body>
</html>

apps/talk/templates/talk/friends.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>친구목록</title>
    <link rel="stylesheet" href="{{ url_for('talk.static', filename='friends.css') }}">

</head>
<body>
    <nav class="navbar">
        <ul>
            <li>
                <a href="{{url_for('talk.friends')}}">
                    <img src="{{url_for('talk.static', filename='dog-friend.jpg')}}">
                </a>
            </li>
            <li>
                <a href="{{url_for('talk.chats')}}">
                    <img src="{{url_for('talk.static', filename='comics.png')}}">
                </a>
            </li>
        </ul>
    </nav>
    <div class="container">
        <header class="header">
            <h3>친구</h3>
            <div class="header-buttons">
                <span class="header-button"></span>
                <span class="header-button"></span>
            </div>
        </header>
        <main class="main-content">
            <div class="profile-section">
                <div class="profile" style="font-size: 1.2em;">
                    <img src="{{url_for('talk.static', filename='bald-eagle.jpg')}}" alt="프로필">
                    <p>코딩개초보</p>
                </div>
                <hr>
                <div class="friends-count">친구 3</div>
                <br>
            </div>
            <div class="friends-list"></div>
                <div class="friend-item">
                    <img src="{{url_for('talk.static', filename='worm.png')}}" alt="지렁이"></div> 
                <div class="friend-item">
                    <img src="{{url_for('talk.static', filename='sea-anemones.jpg')}}" alt="말미잘">
                </div>
                <div class="friend-item">
                    <img src="{{url_for('talk.static', filename='bird.jpg')}}" alt="참새">
                </div>
            </div>
        </main>
    </div>
</body>
</html>

apps/talk/templates/talk/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>muyotalk</title>
    <link rel="stylesheet" href="{{ url_for('talk.static', filename='index.css') }}">
</head>
<body>
    <div class="container">
        <h1 class="index_h1">muyotalk</h1>
        <form action="{{url_for('talk.friends')}}">
            <input type="text" placeholder="계정 (이메일 또는 전화번호)" class="input-field">
            <input type="password" placeholder="비밀번호" class="input-field">
            <input type="submit" value="로그인" class="submit-btn">
        </form>
    </div>
</body>
</html>